/**
 * E2E test: GET /api/openapi.json serves the generated OpenAPI spec.
 *
 * Previously setupOpenAPIEndpoint was never called and stored the document on
 * the Nest app wrapper instead of the Express app, so ApiDocsController
 * always returned 404.
 */

import { Controller, Get, INestApplication } from '@nestjs/common';
import { ApiOkResponse, ApiTags } from '@nestjs/swagger';
import { Test } from '@nestjs/testing';
import * as request from 'supertest';
import { ApiDocsController } from '../../src/config/api-docs.controller';
import { setupOpenAPIEndpoint, setupSwagger } from '../../src/config/swagger.config';

@ApiTags('Properties')
@Controller('properties')
class SampleController {
  @Get()
  @ApiOkResponse({ description: 'List properties' })
  list() {
    return [];
  }
}

async function createApp(): Promise<INestApplication> {
  const moduleRef = await Test.createTestingModule({
    controllers: [ApiDocsController, SampleController],
  }).compile();
  const app = moduleRef.createNestApplication({ logger: false });
  return app;
}

describe('GET /api/openapi.json', () => {
  let app: INestApplication;

  afterEach(async () => {
    await app?.close();
  });

  it('returns the document generated by setupSwagger', async () => {
    app = await createApp();
    const document = setupSwagger(app);
    setupOpenAPIEndpoint(app, document);
    await app.init();

    const res = await request(app.getHttpServer()).get('/api/openapi.json').expect(200);

    expect(res.body.openapi).toMatch(/^3\./);
    expect(res.body.info).toMatchObject({ title: 'PropChain API', version: '2.0.0' });
    expect(res.body.paths).toHaveProperty('/properties');
    expect(res.body.components?.securitySchemes).toHaveProperty('access-token');
    // The ApiDocsController is excluded from the spec itself
    expect(res.body.paths).not.toHaveProperty('/api/openapi.json');
  });

  it('generates a spec when called without a document', async () => {
    app = await createApp();
    setupOpenAPIEndpoint(app);
    await app.init();

    const res = await request(app.getHttpServer()).get('/api/openapi.json').expect(200);

    expect(res.body.openapi).toMatch(/^3\./);
    expect(res.body.paths).toHaveProperty('/properties');
  });

  it('returns 404 when the endpoint was never set up', async () => {
    app = await createApp();
    await app.init();

    await request(app.getHttpServer()).get('/api/openapi.json').expect(404);
  });
});
